from pathlib import Path

import matplotlib.pyplot as plt


# Read the convergence data generated by the primary 1D Picard solver.
script_dir = Path(__file__).resolve().parent
history_path = script_dir.parent / "doublewell-1d-picard-history.txt"
output_path = script_dir / "doublewell-1d-picard-history.png"

iterations = []
relative_error_u = []
relative_error_m = []

with history_path.open(encoding="utf-8") as history_file:
    for line in history_file:
        columns = [column.strip() for column in line.split("|")]
        if len(columns) != 7 or not columns[0].isdigit():
            continue

        iterations.append(int(columns[0]))
        relative_error_u.append(float(columns[2]))
        relative_error_m.append(float(columns[4]))

if not iterations:
    raise RuntimeError(f"No Picard iterations found in {history_path}")


plt.figure(figsize=(10, 6))
plt.semilogy(
    iterations,
    relative_error_u,
    "r-o",
    label=r"Relative error of $u$",
)
plt.semilogy(
    iterations,
    relative_error_m,
    "b-s",
    label=r"Relative error of $m$",
)
plt.axhline(
    y=1e-6,
    color="black",
    linestyle="--",
    alpha=0.6,
    linewidth=1.2,
    label=r"$\epsilon_P=10^{-6}$",
)
plt.title("Picard Iteration History (1D Double-Well Example)")
plt.xlabel("Picard iteration")
plt.ylabel("Relative error")
plt.grid(True, which="both", linestyle="-", alpha=0.5)
plt.xticks(iterations)
plt.xlim(iterations[0] - 0.5, iterations[-1] + 0.5)
plt.legend()
plt.tight_layout()
plt.savefig(output_path, dpi=200)
plt.show()
